### ISSUE TITLE
Visualizer binaryImageStream WebSocket url 

### ISSUE THREAD

**Issue by wxu2016** [Kitware/visualizer#11]
Hi Sebastien,

In VtkRenderer.js binaryImageStream url is set as 
const wsbUrl = `${this.props.connection.urls}b`;

That works for urls such as ws://127.0.1:/ws, but does not work for urls such as "ws://54.66.238.9/proxy?sessionId=5bd66ccf-2d58-11e6-9052-06fddeae017d".

Is anything need to change in Web/Python/vtk/web/server.py?

Thanks
Wei

**Comment by scottwittenburg** [comment]
The second kind of session url you described is designed to be handled by a webserver like Apache.  In that case, you may need to change your Apache rewrite rule to handle it a little differently.  The following example shows how I set mine up recently:

```
# ParaViewWeb websocket proxying
RewriteMap session-to-port txt:/blah/blah/proxy-mapping.txt
RewriteCond %{QUERY_STRING}     ^sessionId=(.*)&path=(.*)$ [NC]
RewriteRule    ^/proxy.*$  ws://${session-to-port:%1}/%2  [P]
```

Hope this helps.

**Comment by wxu2016** [comment]
Hi Scott,

It works. Thanks
