### ISSUE TITLE
Wavelet constant color or colormap

### ISSUE THREAD

**Issue by aronhelser** [Kitware/visualizer#19]
- Use the '+' to add a Wavelet source
- Change to a Volume view
- Change from 'Solid color' to '(p1) RTData'
- Use the gear icon to change colormaps - choose one of the first two, solid purple or solid green
Bug: no change to wavelet display. Is a solid color valid for a wavelet?
Notice that the wavelet also displays nothing when first changed to Volume view - is 'solid color' valid?

In addition:
- Use the bookmark icon to display the color scale bar. 
Bug: for a single color colormap nothing displays. For other colormaps a valid scale bar displays.

**Comment by aronhelser** [comment]
I was able to see some error messages printed if I ran Visualizer using pvpython directly, with --debug:
pvpython "C:\akit\visualizer\server\pvw-visualizer.py" --content "C:\akit\visualizer\dist" --port 8080 --data "C:/akit/data"  --debug 2>&1 | tee debug.txt
This output is _very_ verbose and includes binary data, so search is your friend.

I think we should add a pass-through ability, so the 'Visualizer' command can pass arguments to pvpython that it doesn't recognize.

**Comment by jourdain** [comment]
You can not do Volume rendering on a solid color. You need a scalar for that.

**Comment by aronhelser** [comment]
OK, makes sense. In ParaView, if I add a Wavelet source, the Coloring automatically changes to RTData. Paraview also only allows you choose a color scale, rather than a solid color. 

Are the solid color options added to the colormap list for simplicity? This case might point to the need for them to be separate.

**Comment by jourdain** [comment]
I've pushed a new preset.json with the removed single color.

**Comment by aronhelser** [comment]
Looks like we got all the constant color ones. I seem to have found one other problem colormap. 
Green Linear (9_17f) won't color wavelets or sphere normals for me. Haven't tracked the error yet.

**Comment by aronhelser** [comment]
OK, think we've removed all the problem colormaps. Closing.
