### ISSUE TITLE
Issues starting visualizer

### ISSUE THREAD

**Issue by r-chris** [Kitware/visualizer#21]
I am trying to launch `Visualizer` on an ec2 instance (headless Ubuntu 16.04 server), but it's giving me trouble:

`Visualizer --paraview /home/ubuntu/apps/ParaView-5.3.0-Qt5-OpenGL2-MPI-Linux-64bit/ -p 9090 -s --viewport [1x1024x860]`

```
===============================================================================
| Execute:
| $ "/home/ubuntu/apps/ParaView-5.3.0-Qt5-OpenGL2-MPI-Linux-64bit/bin/pvpython"
|	-dr
|	"/usr/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py"
|	--content
|	"/usr/lib/node_modules/pvw-visualizer/dist"
|	--port
|	9090
|	--data
|	"undefined"
|	--viewport-scale
|	[1
|	--viewport-max-width
|	1024
|	--viewport-max-height
|	860]
===============================================================================

Traceback (most recent call last):
  File "/usr/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py", line 85, in <module>
    from paraview.web import wamp      as pv_wamp
ImportError: cannot import name wamp
```

**Comment by jourdain** [comment]
ParaView 5.3 has some missing dependency on Linux. We fixed it in Master but didn't republish a new binary. So either you will need to build it again via the superbuild or use our 5.2 binaries.

ParaView 5.4 is planned to be release in a month. This should solve that problem.

**Comment by r-chris** [comment]
Ok thanks - that makes a lot of sense now - how about the nightly builds - I see some `Paraview-latest-..Linux...` - those should be based on the fixed master, right ?

**Comment by r-chris** [comment]
Using `ParaView-5.2.0` appears to have other issues when running on an instance without X server:

`Visualizer --paraview /home/ubuntu/apps/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/ -p 9090 -s`

```
===============================================================================
| Execute:
| $ "/home/ubuntu/apps/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/bin/pvpython"
|	-dr
|	"/usr/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py"
|	--content
|	"/usr/lib/node_modules/pvw-visualizer/dist"
|	--port
|	9090
|	--data
|	"undefined"
===============================================================================

2017-04-06 01:16:41+0000 [-] Log opened.
ERROR: In /home/buildslave/dashboards/buildbot/paraview-pvbinsdash-linux-shared-release_opengl2_qt4_superbuild/source-paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 301
vtkXOpenGLRenderWindow (0x443e3a0): bad X server connection. DISPLAY=Aborted (core dumped)
```

**Comment by r-chris** [comment]
Can I conclude that this is not intended to work on a headless ec2 instance?

**Comment by jourdain** [comment]
Yes

**Comment by jourdain** [comment]
I mean ParaView and Visualizer can work on an headless EC2 instance, but you will have to build ParaView with an OSMesa library. The distributed binaries, support CPU rendering but still require a X server. You can see those arguments [here](https://gitlab.kitware.com/paraview/paraview/merge_requests/1150/diffs#d57fe00d6471251942764aa21f98f1c0fb49f69a) to enable that.

**Comment by jourdain** [comment]
You don't loose any capability if you use OSMesa except maybe rendering performance depending on the technology you plan to use and hardware available. Maybe the simplest option would be to use our Docker images for which you can either choose CPU rendering or GPU (for Nvidia via EGL) while both will support offscreen.

You can read more about it [here](http://kitware.github.io/paraviewweb/docs/docker.html) and [here](http://kitware.github.io/paraviewweb/docs/ec2.html)

Although, I'm not sure what you mean by doing remote visualization via ssh as in the case of Visualizer, you connect to a web server using your browser.
