### ISSUE TITLE
Server crash with image encoder, Windows

### ISSUE THREAD

**Issue by aronhelser** [Kitware/visualizer#34]
On windows 10, ParaView 5.4 version or latest version.

run Visualizer, add a sphere source, and color by 'p3 (Normals)'. The server will intermittently segfault. In the visual studio debugger, it's inside a thread wait().

On the latest version, the segfault is very reliable whenever the "pv.color.manager.lut.image.get" RPC call is made twice in a row, as in the above case. 

If I put a `import pdb; pdb.set_trace()` right before the line `b64Str = encoder.EncodeAsBase64Png(imgData, 0)` then the crash is avoided.

So what's up with the threaded encoder?

**Comment by aronhelser** [comment]
If I add:
`time.sleep("0.01")`
right before the encoder call, the crash is avoided for me. Would this be an acceptable hack to fix it?

The other thing I could do would be to remove the use of the encoder and send binary images, but that's a bit more involved.

**Comment by jourdain** [comment]
@aronhelser did you push that code?

**Comment by aronhelser** [comment]
yes, this can be closed.

**Comment by aronhelser** [comment]
I can confirm that the bug still exists on Windows with the ParaView 5.4.1 binaries downloaded from paraview.org. It should be fixed in the next release.

To fix it in 5.4.1, you can do a little patch to your installation of ParaView.

In the file {ParaViewInstallDir}\bin\Lib\site-packages\paraview\web\protocols.py, around line 1070, add these two lines:

        # Use the vtk data encoder to base-64 encode the image as png, using no compression
        encoder = vtkDataEncoder()
+        # two calls in a row crash on Windows - bald timing hack to avoid the crash.
+        time.sleep(0.01);
        b64Str = encoder.EncodeAsBase64Png(imgData, 0)
