### ISSUE TITLE
Unwanted zoom-out change while loading state file (.pvsm) 

### ISSUE THREAD

**Issue by MariDani** [Kitware/visualizer#36]
Hi all,

I have scene in Paraview which looks like this (the data are zoomed in)
![scene_paraview](https://user-images.githubusercontent.com/5398172/28972095-ab85d720-792e-11e7-9672-50900d1124c5.PNG)

When I export this scene to .pvsm file and I load this .pvsm file in Visualizer I get the same view as in Paraview but unfortunately the same view lasts only for 1-2 seconds. Then the zoom is changed by itself (probably to fit all the data to the window) and I get this:
![scene_visualizer](https://user-images.githubusercontent.com/5398172/28972214-1719d70c-792f-11e7-8185-bbc6bdb4bcc2.PNG)

Is there any way to keep the initial zoom, so the Visualizer wouldn't automatically zoom out the scene?

Thank you

Mariana

**Comment by MariDani** [comment]
Hello, and thank you for your answer.
I understand your logic behind it however right now it would be great for me to at least have an option to keep the zoom settings the same as in the paraview state file.
Do you think you could add this option? Or to change the settings in Visualizer so the zoom settings (camera settings) are not reset after state file is loaded?
Thank you
Mariana

**Comment by jourdain** [comment]
Hi Mariana, 

I may have fix the issue here: https://gitlab.kitware.com/paraview/paraview/merge_requests/1833/diffs

But you can edit that file yourself within your ParaView distribution and test it out.

Let me know if that fix your issue.

**Comment by MariDani** [comment]
Hello Sebastien,

awesome, this fixed my issue.

Thank you very much.
