### ISSUE TITLE
Opening Ensight does not detect time

### ISSUE THREAD

**Issue by ArnauMiro** [Kitware/visualizer#39]
Hi,

I've been trying to load time-dependent Ensight files into Visualizer and I noticed that it doesn't detect the time series. When I load in ParaView, the time series is detected normally, but not when I open with Visualizer. 

Loading a state file doesn't help either.

Will this feature be added at some point?

Thanks,

Arnau

**Comment by jourdain** [comment]
This should work. If not, then it can be configured to do so and we should not need to add/edit any code for that.

Do you mind sharing a file that illustrate that issue with me? 

Thanks,

Seb

**Comment by ArnauMiro** [comment]
Here it goes a screen cap of visualizer with Ensight data set loaded


This is paraview opening the same data set




As you can see ParaView detects that is time dependent and loads the time bar, whereas visualizer does not. The data set is a bit big but I can also share it if needed.

If it can be configured, can you please show me how? I would really love to use the visualizer tool but all my data is in Ensight format, so it is a big drawback.

Thanks for the help,

Best,

--
Arnau Miró

**Comment by jourdain** [comment]
If I can get my hand on an Ensight time dataset and see why Visualizer is not picking up its time information, that would be useful. So I can figure out of the issue is in the code or in the config.

You can send me a private e-mail with your data, that would be great. sebastien.jourdain@kitware.com

**Comment by jourdain** [comment]
It worked for me?

![screen shot 2017-08-17 at 11 58 16 am](https://user-images.githubusercontent.com/294518/29426312-78f28cb2-8343-11e7-8234-070c6f79b774.png)

**Comment by jourdain** [comment]
Which version of Visualizer and ParaView are you using?

**Comment by ArnauMiro** [comment]
I'm using Visualizer 2.2.2 and ParaView 5.4.0.

Is it fixed on the latest version? 

--
Arnau Miró

**Comment by jourdain** [comment]
I've tried on pv/master but will try on PV 5.4.0 now.

Which OS are you using?

**Comment by jourdain** [comment]
I managed to reproduce your issue with 5.4.0. 

But it seems to be fixed on ParaView/master. Hopefully 5.4.1 will fix that issue too.

**Comment by ArnauMiro** [comment]
I'm on Ubuntu linux. I'll try with paraview 5.4.1

Thanks,

--
Arnau Miró

**Comment by ArnauMiro** [comment]
I fixed it by installing ParaView/master and running on Visualizer 2.3.0

![q](https://user-images.githubusercontent.com/12005728/29464781-3ead856c-8437-11e7-886a-fe5df5047cb9.png)

Thanks for the help! I'm closing the issue.

**Comment by jourdain** [comment]
Thanks for your feedback and happy that's working for you now... ;-)
