### ISSUE TITLE
Can't find pv_wslink.py in paraview.web in Paraview 5.4  macOS version

### ISSUE THREAD

**Issue by yqrashawn** [Kitware/visualizer#43]
```
node_modules/pvw-visualizer/server/pvw-visualizer.py", line 85, in <module>
    from paraview.web import pv_wslink
ImportError: cannot import name pv_wslink
```
So where should I get those files? Install an old version?

**Comment by jourdain** [comment]
ws_link was introduced in Visualizer 2.3 which would only work with ParaView/master.

You can refer to the compatibility table [here](https://kitware.github.io/visualizer/docs/compatibility.html) or on the main [README](https://github.com/kitware/visualizer#pre-requisite).
