### ISSUE TITLE
ImportError: cannot import name pv_wslink

### ISSUE THREAD

**Issue by defineconst** [Kitware/visualizer#49]
hadoop@ubuntu:~/Downloads/visualizer-master$ /usr/local/bin/Visualizer --data /home/hadoop/Downloads/ParaViewData-v4.4.0 --port 8080 --paraview /home/hadoop/Downloads/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit 

===============================================================================
| Execute:
| $ "/home/hadoop/Downloads/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit/bin/pvpython"
|	-dr
|	"/home/hadoop/Downloads/visualizer-master/server/pvw-visualizer.py"
|	--content
|	"/home/hadoop/Downloads/visualizer-master/dist"
|	--port
|	8080
|	--data
|	"/home/hadoop/Downloads/ParaViewData-v4.4.0"
===============================================================================

Traceback (most recent call last):
  File "/home/hadoop/Downloads/visualizer-master/server/pvw-visualizer.py", line 93, in <module>
    from paraview.web import pv_wslink
ImportError: cannot import name pv_wslink
hadoop@ubuntu:~/Downloads/visualizer-master$

**Comment by jourdain** [comment]
http://kitware.github.io/visualizer/docs/compatibility.html

The version of visualizer you are using is not compatible with the ParaView you have. Either use Visualizer that is [bundle with your ParaView](http://kitware.github.io/paraviewweb/docs/architecture.html#Simplicity) or make sure they are compatible.

**Comment by defineconst** [comment]
3Q
