### ISSUE TITLE
ImportError: cannot import name pv_wslink

### ISSUE THREAD

**Issue by defineconst** [Kitware/visualizer#50]
hadoop@ubuntu:~$ /usr/local/bin/Visualizer --data /home/hadoop/Downloads/ParaViewData-v4.4.0 --port 8080 --paraview /home/hadoop/Downloads/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit 

===============================================================================
| Execute:
| $ "/home/hadoop/Downloads/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit/bin/pvpython"
|	-dr
|	"/home/hadoop/Downloads/visualizer-master/server/pvw-visualizer.py"
|	--content
|	"/home/hadoop/Downloads/visualizer-master/dist"
|	--port
|	8080
|	--data
|	"/home/hadoop/Downloads/ParaViewData-v4.4.0"
===============================================================================

Traceback (most recent call last):
  File "/home/hadoop/Downloads/visualizer-master/server/pvw-visualizer.py", line 93, in <module>
    from paraview.web import pv_wslink
ImportError: cannot import name pv_wslink
hadoop@ubuntu:~$

**Comment by jourdain** [comment]
```
$ npm install -g pvw-visualizer@2.2.0
$ /usr/local/bin/Visualizer --data /home/hadoop/Downloads/ParaViewData-v4.4.0 --port 8080 --paraview /home/hadoop/Downloads/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit
```

**Comment by defineconst** [comment]
3Q
