### ISSUE TITLE
how to use texture

### ISSUE THREAD

**Issue by tomhaitao** [Kitware/visualizer#53]
Is there this component in the 2.2 version?   Similar to the texture component in parview

**Comment by tomhaitao** [comment]
I would like to ask if there is a similar component in visualizer：<img width="345" alt="qq20180420-091046 2x" src="https://user-images.githubusercontent.com/15882629/39025961-c75f2856-447c-11e8-8220-52501f7863e3.png">.
I've added ‘texture map to plane’ to the python code, but I don’t know how to load the texture image

**Comment by jourdain** [comment]
Yes that panel is not implemented in Visualizer which prevent you from doing it.

But if you extend the server code you could enable that. Here is an example on how Textures are managed in Python with ParaView:
https://github.com/Kitware/vtk-js/blob/master/Utilities/ParaView/obj-mtl-importer.py#L242-L249
