### ISSUE TITLE
Volume rendering, --proxies

### ISSUE THREAD

**Issue by Alex9025** [Kitware/visualizer#54]
Hi all,

Paraviewweb/Visualizer is a very useful tool for demonstration and communication between collaborators working on a project. Here are some problems when testing Visualizer :

(1) I tried to visualize volume data (4 unsigned char components : RGB + opacity) with Visualizer ( the version in ParaView-5.5.0-Qt5-MPI-Linux-64bit), the file is loaded correctly in Visualizer, I uncheck the checkbox "Map Scalars" so that it can directly interpret colors, but I cannot get right volume rendering, it seems that for the opacity it chooses Magnitude instead of taking the last component. I also tried with the nightly build version (ParaView-5.5.0-342-g968ff44-Qt5-MPI-Linux-64bit), which has a new checkbox "Multi Components Mapping" for multi component array, but checked or not, it does not solve the problem. However the visualization works perfectly on Paraview. Could you advise me what to do?

(2) Is it possible to start Visualizer with different defaut settings (check or uncheck checkboxes, specify background color, etc)? 

(3) It is interesting to be able to add other readers and filters via the --proxies option, but strangely it crashes, even with the defaut proxies : 

```
/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/bin/pvpython -dr /home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/share/paraview-5.5/web/visualizer/server/pvw-visualizer.py --content /home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/share/paraview-5.5/web/visualizer/www/ --port 8080 --data /home/alex/dev/Data/ --proxies /home/alex/dev/test/defaut_proxies.json
Traceback (most recent call last):
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/share/paraview-5.5/web/visualizer/server/pvw-visualizer.py", line 241, in <module>
    server.start_webserver(options=args, protocol=_VisualizerServer)
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/wslink/server.py", line 180, in start_webserver
    wslinkServer = protocol()
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/web/pv_wslink.py", line 12, in __init__
    vtk_wslink.ServerProtocol.__init__(self)
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/vtkmodules/web/wslink.py", line 44, in __init__
    websocket.ServerProtocol.__init__(self)
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/wslink/websocket.py", line 62, in __init__
    self.initialize()
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/share/paraview-5.5/web/visualizer/server/pvw-visualizer.py", line 192, in initialize
    self.registerVtkWebProtocol(pv_protocols.ParaViewWebProxyManager(allowedProxiesFile=_VisualizerServer.proxies, baseDir=_VisualizerServer.dataDir, fileToLoad=_VisualizerServer.fileToLoad, allowUnconfiguredReaders=_VisualizerServer.allReaders))
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/web/protocols.py", line 1597, in __init__
    self.readAllowedProxies(allowedProxiesFile)
  File "/home/alex/dev/ParaView-5.5.0-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/web/protocols.py", line 1632, in readAllowedProxies
    with open(filepath, 'r') as fd:
NameError: global name 'filepath' is not defined
```

All suggestions and answers are welcome!

Alex

**Comment by jourdain** [comment]
Hi Alex,

Thanks for reporting the issue you encounter. 

1) I believe we don't have the proper UI or server side logic when doing volume rendering with RGBA data. But if you're goal is to share some data without the generic filtering of Visualizer, it would be fairly easy to create a custom ParaViewWeb application focusing on your data with the correct rendering.

2) I've never tried, but ParaView have some infrastructure to customize the defaults via some JSON files. I believe those same settings could most likely be loaded inside Visualizer with little code modification.

3) Definitely looks like a bug. Thanks for reporting...

**Comment by jourdain** [comment]
The [PR](https://gitlab.kitware.com/paraview/paraview/merge_requests/2465/diffs) should fix (3).

**Comment by jourdain** [comment]
For 1, if you can share a small RGBA volume with me, I can investigate what could be missing.

Thanks,

Seb

**Comment by Alex9025** [comment]
Thank you for your prompt response, Sebastien. Yes, maybe it's better to write a custom application with ParaViewWeb. I have just discovered Paraviewweb and Visualizer, I suppose there are many examples of applications. 
Here is the link of a RGBA volume file :
[https://drive.google.com/file/d/11rmTxZTBkcvbjK-5IQ22qo0Ju33FV4HT/view?usp=sharing]()
It seems that colors of the volume are correctly interpreted, but the opacity transfer function matches Magnitude, not the alpha component.

Thanks,
Alex

**Comment by jourdain** [comment]
Loading the data in ParaView does not seems to properly understand the RGBA even by toggling of the "Map Scalars". Although, I might have done something wrong since I was not fully focused on that task. Do you mind posting a screenshot of the Visualization you think is correct?

**Comment by Alex9025** [comment]
I think the problem is that on Visualizer, the (default) opacity transfer function is defined between the min and the max of Magnitude which are 229 and 451 for this volume, under 229 the opacity is 0, but the alpha component of the volume is from 0 to 115, and this function is actually applied on alpha component,  so we do not see anything. 
The definition of the opacity transfer function should match the range of the alpha component, not that of Magnitude.

**Comment by jourdain** [comment]
I see

**Comment by jourdain** [comment]
Since the issue is the scaling, you can manually set the range and even adjust the opacity transfer function.

<img width="1155" alt="screen shot 2018-05-21 at 4 15 17 pm" src="https://user-images.githubusercontent.com/294518/40332713-4d389414-5d12-11e8-9da2-64e5278d7024.png">

**Comment by jourdain** [comment]
I picked a weird color map to make sure the data was not interpreted as scalar and mapped with the Lookup table.

**Comment by Alex9025** [comment]
That's really great, thank you!

**Comment by jourdain** [comment]
If you download the nightly binary tomorrow, you'll get the fix for the `--proxies ...` ;-)

**Comment by Alex9025** [comment]
What good news, it's fantastic! ;-)))

**Comment by Alex9025** [comment]
For the scaling of opacity transfer function, is it also possible to change?

**Comment by jourdain** [comment]
Yes just type what ever range you want and click on the "guy" icon to apply.

Also changing the shape of the transfer function will affect it as well.

**Comment by Alex9025** [comment]
Yes, manually I can change the range. Is it possible that the definition of the transfer opacity function matches automatically the range of the alpha component, as on ParaView?

**Comment by jourdain** [comment]
Not automatically, but if you look at the info tab, you can get the exact range.

**Comment by Alex9025** [comment]
Yes, it's true. Is it possible to load a transfer function as on Paraview?

**Comment by jourdain** [comment]
not right now

**Comment by Alex9025** [comment]
Thank you very much for all these answers and information, things are much clearer now.

**Comment by Alex9025** [comment]
Hi Sebastien, 
I still have a question about the opacity transfer function, if we would like to set the range (the same for all volumes), say between 0 and 255, which part of the code should be changed?

Thank you.

**Comment by jourdain** [comment]
Just put [0,255] instead of my [0, 120] of my screenshot.

**Comment by Alex9025** [comment]
Is it possible to change the code, so that each time when a volume is loaded, the range is automatically [0,255] ?

**Comment by jourdain** [comment]
It would be easy to handle in a custom application but with Visualizer, it is possible the app will try by default to auto find a good value which may not work for your dataset.

If the file to load is provided as argument at startup, you should be able to execute custom code right after the app is loaded to adjust some parameters. But if it is dynamically loaded, you will have to tweak the methods to update the various proxy which may not be as trivial. 

FYI, this is the [piece of code](https://github.com/Kitware/ParaView/blob/master/Web/Python/paraview/web/protocols.py#L1128-L1139) that get executed when you click on the `custom` range from the UI.

**Comment by Alex9025** [comment]
Thank you for your reply.
A question about the default form of the opacity transfer function, it does not look like a strict piecewise linear function, if we want just a simple piecewise linear function, for instance 0 at min and 1 at max,  is that possible (for the cost a "small" modification of the code)?

**Comment by jourdain** [comment]
Yes, that could be part of the custom code execution, but currently the UI will always show a gaussian.
And I'm pretty sure the initial value (if you don't touch the gaussian) is a true linear piecewise function regardless of what it is shown in the client side ui.

**Comment by Alex9025** [comment]
I understand now, It's a Gaussian, so it's smooth. Even if at the beginning it is linear but the initial value (at min) is not 0 ( perhaps very close to 0),  because after putting the a new range [0, 255], we can see that there is fog in the area that is normally transparent (alpha component = 0).

**Comment by Alex9025** [comment]
This is a screenshot of fog
![volume-fog](https://user-images.githubusercontent.com/39485290/40499555-9113b700-5f82-11e8-94ef-2208a87345f6.png)

**Comment by Alex9025** [comment]
Is it possible to set the opacity equal to 0 at min ?

**Comment by jourdain** [comment]
Yes with what I previously said.
