### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'showBuiltin'

### ISSUE THREAD

**Issue by shariefyoussef** [Kitware/visualizer#55]
Hi I cloned the code and installed, built. When I run Visualizer, I get the following error:

Visualizer -p 8181 --paraview /Applications/3D-Software/ParaView-5.5.0.app -d ~/Develop/data

:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

Traceback (most recent call last):
  File "/Users/ssy/Develop/visualizer/server/pvw-visualizer.py", line 243, in <module>
    server.start_webserver(options=args, protocol=_VisualizerServer)
  File "/Applications/3D-Software/ParaView-5.5.0.app/Contents/Python/wslink/server.py", line 180, in start_webserver
    wslinkServer = protocol()
  File "/Applications/3D-Software/ParaView-5.5.0.app/Contents/Python/paraview/web/pv_wslink.py", line 12, in __init__
    vtk_wslink.ServerProtocol.__init__(self)
  File "/Applications/3D-Software/ParaView-5.5.0.app/Contents/Python/vtkmodules/web/wslink.py", line 44, in __init__
    websocket.ServerProtocol.__init__(self)
  File "/Applications/3D-Software/ParaView-5.5.0.app/Contents/Python/wslink/websocket.py", line 62, in __init__
    self.initialize()
  File "/Users/ssy/Develop/visualizer/server/pvw-visualizer.py", line 195, in initialize
    self.registerVtkWebProtocol(pv_protocols.ParaViewWebColorManager(pathToColorMaps=_VisualizerServer.colorPalette, showBuiltin=_VisualizerServer.showBuiltin))
TypeError: __init__() got an unexpected keyword argument 'showBuiltin'

**Comment by jourdain** [comment]
Visualizer 3.1.4 is the one compatible with 5.5.
For Visualizer 3.1.5, you need paraview/master.

The compatibility table is available [here](https://kitware.github.io/visualizer/docs/compatibility.html)

**Comment by Trophime** [comment]
What about Visualizer 3.1.10? Is it compatible with ParaView 5.6.0?

**Comment by jourdain** [comment]
Yes, that's probably the one that get's bundle inside the ParaView binaries.

**Comment by Trophime** [comment]
Thanks.

I still have an other question (maybe stupid one)
Following the docs I've tried:
```Visualizer --paraview /Applications/paraview.app --data dir```
where dir is the directory with my results (ensigth case)

But I got only an "empty" window...
I'm wondering what kind of argument is actually requirered for `data`.
It's not clear for me. Could you provide some data to check the install?

**Comment by Trophime** [comment]
Right now I would like to check if it's working... 
I could start with pre-load a file
but The ideal situation would be that the user pick the file they want from that directory

**Comment by jourdain** [comment]
Ok so, I believe the issue was that you were not using a full path for the `--data` argument. Unless you don't know how to load a file from the Web UI after the application is starting?

**Comment by Trophime** [comment]
Actually, I don't understand how to load a file.

**Comment by jourdain** [comment]
Ok then click on the icon that looks like a file. The panel will change to a list with all the files and directories that are below the specified directory on the server side.
![visualizer](https://user-images.githubusercontent.com/294518/48272412-beab6480-e3fb-11e8-9450-052dbf963821.jpeg)

**Comment by Trophime** [comment]
The point is I don't see any icons.
What I've got looks like that:
![visualizer](https://user-images.githubusercontent.com/1309311/48272476-f687cb80-e43e-11e8-99cf-4ffadda04390.png)

I've created a dockerfile (build with latest mesa 18.2.4) for Visualizer.
Then start the container interactively and just run `Visualizer ...`

**Comment by jourdain** [comment]
Wait what? You should probably start a new thread explaining what you did. 
This is definitely off that `__init__()` error topic.

When you use our docker image with Viasualizer, you don't need to run the Visualizer command line. The docker give you a web server that you need to access via your browser.

When you run that command line, it looks like a server is running on `http://localhost:8080/`.

**Comment by Trophime** [comment]
> When you use our docker image with Viasualizer
Actually I've not found the docker for that part so I've tried to create my own... that's why...
Is the Visualizer docker image publicly available?

**Comment by jourdain** [comment]
Yes, you can even use our latest demo one which provide all the other webapps at the same time that are bundled within ParaView binaries.

The images are available here: https://hub.docker.com/r/kitware/paraviewweb/tags/

The documentation on how to use the visualizer one is available here: http://kitware.github.io/paraviewweb/docs/ec2.html

If you use `pvw-egl-demo-v5.6.0`  you will have a full web server with a welcome page and all the web apps.

**Comment by Trophime** [comment]
Thanks a lot.
