### ISSUE TITLE
Customizing Visualizer App

### ISSUE THREAD

**Issue by Sagar-Shimpi** [Kitware/visualizer#61]
Hi,

I am working on Paraview and its web applications such as LightViz, Visualizer.
I want to know, from where exactly I can customize the Visualizer application?
Customization regards to the addition of a button/text or changing entire UI.
I have tried changing js files from React/Widgets directory of paraviewweb, but found no changes were reflected. May I know where exact files are located?

Thanks in advance!!!

Regards,
Sagar

**Comment by jourdain** [comment]
The UI from Visualizer is made by those [components](https://github.com/Kitware/visualizer/tree/master/src/panels).

Just make sure you build the app again (`npm run build`). Also make sure to point to the newly generated application (`[...] --content ./dist`).

**Comment by Sagar-Shimpi** [comment]
Thank you for the reply. It's working.
