### ISSUE TITLE
I can't display the model immediately when I switch to local rendering

### ISSUE THREAD

**Issue by HLshushu** [Kitware/visualizer#65]
Hello all,
  When I switch from remote rendering to local rendering, I need to drag my model to see the rendering results. I want to know the problem.
**switch to local rendering**
![image](https://user-images.githubusercontent.com/41134080/45660438-58a50e00-bb2b-11e8-95a9-34ece0af07d8.png)
**drag model**
![image](https://user-images.githubusercontent.com/41134080/45660462-78d4cd00-bb2b-11e8-8191-edad7e9448d6.png)

**Comment by jourdain** [comment]
You may have to call reset camera at first then the camera should remain in synch.
But it is most likely a bug.

**Comment by HLshushu** [comment]
Thank you for your advice, but it doesn't work. I also think it is a bug.

**Comment by jourdain** [comment]
Same as remote rendering. Just drag with left button. Did you click on the button to “reset the camera “ first?

**Comment by HLshushu** [comment]
My idea is not the operation of the interface, but the modification of the code. Clicking on the button to "reset the camera" first can indeed display the model, but I think local rendering can display it like the remote rendering when loading.

**Comment by jourdain** [comment]
1) If you want that the local rendering show the same thing/position as remote, I’ve already acknowledged the bug which only appears the very first time. 

2) If you are asking how you can extend the current code base so when you click on a button (or at startup), you want a specific camera position, then it’s another story. 

Which one is it? 1 or 2?

**Comment by jourdain** [comment]
Did you try with ParaView 5.6? I can't reproduce the issue. We may have fixed it when improved the vtk.js integration.

**Comment by jourdain** [comment]
Actually I was able to reproduce the issue if we load the off-center model while in local rendering. While if you switch from remote rendering to local rendering, then everything is fine as the camera get properly synchronized.

Basically the client should call resetCamera the first data we load. This is automatically done on the server side, but that logic does not exist in our client. Hence the issue with the LocalRendering. 

I'll see what I can do... Thanks for reporting the issue!

**Comment by jourdain** [comment]
Release 3.1.10 should fix that
