### ISSUE TITLE
Fully working demo - example in repository doesn't work

### ISSUE THREAD

**Issue by vsoch** [Kitware/visualizer#67]
Hi again!

I've been trying for a few days to just get a basic demo up and running. I was first trying with a Singularity container, and have defaulted back to using the Dockerfile you have under "demo." I am following the instructions and for the life of me I can't get it working. The start command seems to hang:

```bash
$ docker run -p 127.0.0.1:8081:80 -ti paraview ws://localhost:8081
Starting/Restarting Apache webserver
 * Restarting Apache httpd web server apache2                                   AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
                                                                         [ OK ]
Starting the wslink launcher
```
Then the mapping to 127.0.0.1 doesn't work, but I can go to 172.17.0.2, but the links are all dead (permission denied)

![image](https://user-images.githubusercontent.com/814322/48956310-635f9300-ef20-11e8-94ed-72634c518333.png)

Then I browse to visualizer, for example, and it waits for a bit that it's loading paraview

![image](https://user-images.githubusercontent.com/814322/48956331-7e320780-ef20-11e8-933a-ca1d05ff9f79.png)

but ultimately fails:

![image](https://user-images.githubusercontent.com/814322/48956341-8b4ef680-ef20-11e8-8912-6ae19b642743.png)

Can you please provide a clean set of commands to reproduce your working demo? Thank you!

**Comment by jourdain** [comment]
Did you read the guide for it available [here](http://kitware.github.io/paraviewweb/docs/docker.html)?

If you are on mac, you can not use the EGL version as you don't have the Nvidia hardware.

**Comment by vsoch** [comment]
Why would I need a separate apache configuration on my host?

**Comment by vsoch** [comment]
And no way, I would never have a Mac :P

**Comment by vsoch** [comment]
oh hold the phone! I see the bottom, let me try that!

**Comment by jourdain** [comment]
Don't skip the nvidia runtime...

**Comment by vsoch** [comment]
I don't have an nvidia runtime...

**Comment by jourdain** [comment]
So you'll need the osmesa version of the image but the rendering perf will suck...

**Comment by vsoch** [comment]
Without the runtime:

```bash
$ docker run -p 127.0.0.1:8081:80 -ti paraview ws://localhost:8081
```
I can see the first screen, progress!

![image](https://user-images.githubusercontent.com/814322/48956606-f2b97600-ef21-11e8-9678-76965e942323.png)

But the application still is terrible.

It's okay if the performance sucks now, I just want to get this working locally (to then provide as a container for users in an environment that *does* have the runtime.

**Comment by jourdain** [comment]
If you don't have the nvidia runtime, like on my mac, you would need to run the following command line that will use your CPU to do the rendering.

```
docker run -p 0.0.0.0:9000:80 -v ~:/data -ti kitware/paraviewweb:pvw-osmesa-demo-v5.6.0 "ws://localhost:9000/" "-dr" "--mesa-swr"
```

**Comment by vsoch** [comment]
Okay, got the visualizer! 

![image](https://user-images.githubusercontent.com/814322/48957561-3fec1680-ef27-11e8-9933-ddf13b137bf8.png)

@trophime you reported not getting this to work - did either of the above work for you? Note that I did the following for each, and the second (no nvidia) worked on my laptop. I also didn't mount my home to the container because this is terrifying.

You can do the below on a Mac with Nvidia runtime:

```bash
docker run -p 0.0.0.0:9000:80 -ti kitware/paraviewweb:pvw-egl-demo-v5.6.0 "ws://localhost:9000/"
```

On a computer without (like mine)

```bash
docker run -p 0.0.0.0:9000:80 -ti kitware/paraviewweb:pvw-osmesa-demo-v5.6.0 "ws://localhost:9000/" "-dr" "--mesa-swr"
```

For both of the above, it didn't seem to map to localhost, but it was able to spit out the Docker host in the console for me to see. @trophime if you can confirm one of the above works in your environment, I think that is enough to move and debug with Singularity (and close this particular issue).

**Comment by jourdain** [comment]
For the nvidia hardware for which you need the runtime, you are missing `--runtime=nvidia`.

**Comment by vsoch** [comment]
Fixed!

**Comment by jourdain** [comment]
BTW the nvidia runtime can only work on Linux not mac.

**Comment by vsoch** [comment]
Yeah I think @trophine is testing in a cluster (HPC) environment with nvidia drivers, so he should be good. I'm on an old Thinkpad with Ubuntu and I've disabled most graphics cards extra features, so I'm just the weird case :)

**Comment by vsoch** [comment]
hey @jourdain I think @trophime might be sleeping (in France or a different time zone) so I want to help him  out. I've got the second (non nvidia) built into a Singularity container, and I'm getting a server error (400, likely because it can't write to somewhere).

![image](https://user-images.githubusercontent.com/814322/48961256-1213cb80-ef41-11e8-8bc7-e56639d21221.png)

Are you able to tell me where in the container we would need to have write (for logging, etc.?) I would need to bind that to the host at runtime.

**Comment by jourdain** [comment]
Apache will try to write some log files:
https://github.com/Kitware/paraviewweb/blob/master/tools/docker/paraviewweb/config/apache/001-pvw.conf#L5-L6

Then the launcher will do the same here:
https://github.com/Kitware/paraviewweb/blob/master/tools/docker/demo/config/launcher/launcher-template.json#L7
https://github.com/Kitware/paraviewweb/blob/master/tools/docker/demo/config/launcher/launcher-template.json#L15

HTH

**Comment by vsoch** [comment]
That's not only helps, it's exactly what I needed! I just produced a fully working [Singularity container](https://github.com/singularityhub/paraviewweb-apache#singularity). Thanks for all your help @jourdain, closing issue.
