### ISSUE TITLE
Install on Mac OSX Sierra seems incomplete

### ISSUE THREAD

**Issue by cbresloff** [Kitware/visualizer#68]
I have Paraview 5.6.0 and Visualizer 13.1.10 installed on a MAcOSX Sierra system.  I have both Python 2.7 and 3.2 installed; both Python versions have 'service_indentity' installed.  However, when I try to launch the Visualizer with:

Visualizer --paraview /Applications/paraview.app --data ~/Desktop

I get: 

===============================================================================
| Execute:
| $ "/Applications/ParaView-5.6.0.app/Contents/bin/pvpython"
|	-dr
|	"/usr/local/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py"
|	--content
|	"/usr/local/lib/node_modules/pvw-visualizer/dist"
|	--port
|	8080
|	--data
|	"/Users/cynthia/Desktop"
===============================================================================

:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
wslink: Starting factory
CRITICAL:twisted:wslink: Starting factory

And I have a very small window pop up with the 3 axis icon, but no tab or windows bar.  It appears to not be launching properly, and I don't know why the 'service_identity' warning is coming up, when it is indeed installed.

**Comment by jourdain** [comment]
To me it seems to work. You need to open your browser at `http://localhost:8080/`.

**Comment by jourdain** [comment]
BTW, the path to Paraview provided is invalid but it managed to find the right ParaView so you could skip the `--paraview` arg and just run: `Visualizer --data ~/Desktop`.

**Comment by cbresloff** [comment]
Seems you are right; I can launch it on the localhost.
