### ISSUE TITLE
Cell selection and querying data

### ISSUE THREAD

**Issue by nandangokhale** [Kitware/visualizer#70]
Thank you for developing this tool - we have just started playing around with it and have found it very useful. Is it possible to 'select cells' via mouse clicks, and then query the data using something like the 'Find Data' feature in Paraview desktop? Or is there any documentation we could start from in order to implement such a feature?

Thank you.

**Comment by jourdain** [comment]
In that specific use case we are missing the client side UI to achieve that. Such feature could be added but would require either community contribution or funding so we could implement it.

You might be able to find information in the ParaView documentation, by looking at how to perform selection in Python. The cell/point selection api is already implemented at the network level and we are just missing the UI. For the FindData, I haven't looked at how it is done but it rely on the same selection mechanism.

HTH,

Seb

**Comment by nandangokhale** [comment]
Great, thanks for the info.
