### ISSUE TITLE
Inconsistency between given proxies.json and the ParaView one

### ISSUE THREAD

**Issue by CharlesGueunet** [Kitware/visualizer#72]
When no `--proxies` are given, ParaView Web use its default one (in *Web/Python/paraview/web/_default_proxies.py*). This default one is not the same as the default one provided by visualizer in *server/proxies.json*, as there is an additional line in the visualizer file:
`        { "name": "VERAOUTReader", "extensions": [ "h5" ], "method": "FileName" }`

**Comment by jourdain** [comment]
The proxy files is something given as an example. The Default in ParaView is to ask when several readers are available. In Visualizer we can't ask the user to dynamically pick reader therefore a choice was made base on our needs. If you expect another choice, please change the file locally for your needs.
