### ISSUE TITLE
nvidia IndeX representation

### ISSUE THREAD

**Issue by memphizz** [Kitware/visualizer#73]
Is there a way to make nvidia IndeX representation available to visualizer?

**Comment by jourdain** [comment]
Yes, nvidia has been playing with both Optix and IndeX. You just need a ParaView built with it and Visualizer will expose those rendering options.

**Comment by memphizz** [comment]
Thanks for reply. I got indeX to work using ParaView-5.6.0-RC3-MPI-Linux-64bit. Do you know of binaries that come with Optix?

**Comment by jourdain** [comment]
Not me but I reached out to the Nvidia folks to let them know about this issue. They might get back to you with additional informations. Anyhow, you could also use ParaView Discourse to ask about ParaView+IndeX/OptiX availability.

**Comment by tbiedert** [comment]
[This MR](https://gitlab.kitware.com/vtk/vtk/merge_requests/5189) contains our new [VisRTX](https://github.com/NVIDIA/VisRTX)/OptiX-based backend for VTK/ParaView.

Please note that this is still work in progress.   Thanks for your interest, and your patience! :-)

**Comment by memphizz** [comment]
I am using IndeX in Visualizer (hopefully soon trying OptiX) for rendering 3D microscopy data. So far we are impressed by the quality and speed of the rendering. We are also looking into ways of integrating Visualizer with OMERO (https://www.openmicroscopy.org/omero/) which is microscopy image management environment.

**Comment by jourdain** [comment]
If you want [Kitware can help](https://www.kitware.com/what-we-offer/#custom_solutions) in that integration as well as customizing the web app itself to better fit your needs.

**Comment by memphizz** [comment]
Sounds great. I work for the department of developmental neurobiology in St. Jude Children's Research Hospital (https://www.stjude.org/). There are many labs in our institution that would benefit from integration of OMERO and Visualizer. What's the best way to kick start this?

**Comment by jourdain** [comment]
You can probably just post a request [here](https://www.kitware.com/contact-us/) and someone from our team will be able to get back to you.
