### ISSUE TITLE
 Error: Cannot import vtkPVAnimation while building ParaView with python 3

### ISSUE THREAD

**Issue by Shaileshbg1** [Kitware/visualizer#75]
Hello, 

I have been at this issue for quite some time now. But still, I am not getting a way to successfully build ParaView with python3. 
I followed the documentation at https://github.com/Kitware/ParaView/blob/master/Documentation/dev/build.md

This is my cmake command:
`cmake -GNinja ../ -DPARAVIEW_BUILD_QT_GUI=OFF -DPARAVIEW_USE_MPI=ON -DPARAVIEW_ENABLE_PYTHON=ON -DPARAVIEW_ENABLE_WEB=ON -DPARAVIEW_BUILD_ALL_MODULES=OFF -DPARAVIEW_USE_MPI_SSEND=ON -DPARAVIEW_USE_ICE_T=ON -DPARAVIEW_USE_QTHELP=OFF -DENABLE_osmesa:BOOL=ON -DENABLE_qt5:BOOL=OFF `-DENABLE_ffmpeg:BOOL=ON`

After building I get this error:
`Error: Cannot import vtkPVAnimation'

I require vtkPVAnimation because I am using GetAnimationScene() and UpdateAnimationUsingDataTimeSteps() functions, after using LegacyVTKReader to load vtk data from openFoam simulation.

To check if the files have been built, I did a diff between the vtkmodules in the python2.7 built official binary and the vtkmodules which I have built. I found that my build has these many files missing. Here . represents the vtkmodules drectory of the official binaries

`Only in .: vtkPVAnimation.py
Only in .: vtkPVAnimationPython.so
Only in .: vtkPVCatalyst.py
Only in .: vtkPVCatalystPython.so
Only in .: vtkPVClientServerCoreCore.py
Only in .: vtkPVClientServerCoreCorePython.so
Only in .: vtkPVClientServerCoreDefault.py
Only in .: vtkPVClientServerCoreDefaultPython.so
Only in .: vtkPVClientServerCoreRendering.py
Only in .: vtkPVClientServerCoreRenderingPython.so
Only in .: vtkPVCommon.py
Only in .: vtkPVCommonPython.so
Only in .: vtkPVPythonAlgorithm.py
Only in .: vtkPVPythonAlgorithmPython.so
Only in .: vtkPVPythonCatalystPython.so
Only in .: vtkPVServerImplementationCore.py
Only in .: vtkPVServerImplementationCorePython.so
Only in .: vtkPVServerImplementationRendering.py
Only in .: vtkPVServerImplementationRenderingPython.so
Only in .: vtkPVServerManagerApplication.py
Only in .: vtkPVServerManagerApplicationPython.so
Only in .: vtkPVServerManagerCore.py
Only in .: vtkPVServerManagerCorePython.so
Only in .: vtkPVServerManagerDefault.py
Only in .: vtkPVServerManagerDefaultPython.so
Only in .: vtkPVServerManagerRendering.py
Only in .: vtkPVServerManagerRenderingPython.so
Only in .: vtkParaViewWebCore.py
Only in .: vtkClientServer.py
Only in .: vtkClientServerPython.so
Only in .: vtkPythonInterpreter.py
Only in .: vtkPythonInterpreterPython.so
Only in .: vtkRenderingParallelLIC.py
Only in .: vtkRenderingParallelLICPython.so'

And many other files which I have explicitly switched off in my build as I do not require them (like vtk extensions.)   

I have been playing around with many build options, which I thought was related to this, but to no use.
Could you please let me know which build setting I have to enable so that vtkPVAnimation is built in this setting. Any suggestion would be greatly appreciated.

Regards,
Shailesh

**Comment by jourdain** [comment]
Since it is a ParaView question, can you post it on https://discourse.paraview.org/c/paraview-support

**Comment by Shaileshbg1** [comment]
Thank you, I have raised this in ParaView support. Closing this issue.
