### ISSUE TITLE
Can't build Visualizer in development

### ISSUE THREAD

**Issue by hayley-leblanc** [Kitware/visualizer#81]
Hello! I am working with ParaView Visualizer and I want to disable remote rendering. My current instance of ParaViewWeb and the Visualizer were downloaded from https://www.paraview.org/download/, so I didn't have to build them, but since I need to change the ParaView source code, I've been trying to set it up as described here https://github.com/Kitware/visualizer#development. However, I'm running into `npm` issues when I do so - when I run `npm run build`, I get some errors about missing `babel` presets/plugins. I was able to resolve some of them on my own by just installing them using `npm`, but now I'm getting the error `Plugin/Preset files are not allowed to export objects, only functions.` when I try to run `npm run build`. Is this issue probably on my end, or is it an issue with the Visualizer? Thanks so much!

**Comment by jourdain** [comment]
Did you run `npm install`?
Are you on Windows?

**Comment by hayley-leblanc** [comment]
I did run `npm install` and I am on Linux Mint.

**Comment by hayley-leblanc** [comment]
I also tried on a Mac and ran into the same error.

**Comment by jourdain** [comment]
I've just tried it on my mac and I can indeed reproduce the issue. I'll see what I can do to solve it.
You might be able to checkout older version to start working on removing the remote rendering part. Sorry for the inconvenience.

**Comment by jourdain** [comment]
It seems that the issue is out of our end. I hope npm will solve the issue on their server.

https://npm.community/t/dependencies-reported-by-npm-does-not-match-package-json/9478

**Comment by hayley-leblanc** [comment]
Thank you!
