### ISSUE TITLE
CSVReader not importing dataset?

### ISSUE THREAD

**Issue by plasmapotential** [Kitware/visualizer#85]
When I try to use the CSVReader to import a csv into the pipeline, nothing happens.  I can use the ParticlesReader just fine, but CSVReader does not seem to work. Is this a bug or is CSVReader not supported in Paraviewweb?  The CSV I am trying to read is imported in desktop Paraview without any problems.  I am using 5.7.

Here is my proxies.json:

{
    "readers": [  
      { "name": "CSVReader", "extensions": [ "csv" ], "method": "FileNames" },  
      { "name": "STLReader", "extensions": [ "stl" ], "method": "FileNames" },  
      { "name": "LegacyVTKReader", "extensions": [ "vtk" ], "method": "FileNames" },  
      { "name": "VERAOUTReader", "extensions": [ "h5" ], "method": "FileName" }  
  ],  
    "sources": [  
      { "name": "Text" }  
    ],  
    "filters": [  
        { "name": "ProgrammableFilter", "label": "Programmable Filter"},  
        { "name": "Calculator" },  
        { "name": "TableToPoints", "label": "Table To Points" }  
    ]  
}

**Comment by jourdain** [comment]
`{ "name": "CSVReader", "extensions": [ "csv" ], "method": "FileName" },`

**Comment by plasmapotential** [comment]
Thanks for the quick response! I have tried with an 's' and without an 's' and neither seem to work.  Any other ideas?  I have also tried with/without headers.

**Comment by jourdain** [comment]
I guess, I'll have to try, but the trace in ParaView showed me that it was without `s`.
The possible issue is related to the fact that the output does not have a 3D representation.

**Comment by plasmapotential** [comment]
I was wondering if the fact that CSVReader outputs a table, and Paraviewweb doesn't seem to support tables, was the reason why.  Usually my pipeline in desktop paraview is CSVReader => TableToPoints => someotherfilter.  Thanks for confirming that it was without an s.

I could also code a macro to do the CSV importation, but it seems that I cannot load macros in the web version of paraview?  Is there a way to load a user defined pvpython module when running paraviewweb?

**Comment by jourdain** [comment]
You can create and load Python plugin that could be a modified CSVReader3D(CSVReader+TableToPoint)

**Comment by plasmapotential** [comment]
Awesome.  So I can just change PV_PLUGIN_PATH environment variable to the path of my plugin before running my paraviewweb shell command?  Would I need to do anything else to get the plugin to appear in the html web interface?

**Comment by jourdain** [comment]
Not even, you should be able to just run your visualizer command line with an add-on argument like `--plugins /path/to/MyCSVReader.py`.

Then you need to register your new reader with csv extension so it will super seed the standard CSVReader in the `proxies.json` file like you did.

**Comment by plasmapotential** [comment]
Wow perfect thanks so much for the quick response and solution!

**Comment by plasmapotential** [comment]
You mentioned CSVReader3D earlier.  Is this a plugin that already exists?  If so, where would I find it?

**Comment by jourdain** [comment]
That plugin does not exist. It was just to illustrate that the name needs to be different to prevent conflict.

**Comment by jourdain** [comment]
Look at [that file](https://github.com/Kitware/ParaView/blob/master/Examples/Plugins/PythonAlgorithm/PythonAlgorithmExamples.py) for example.

**Comment by plasmapotential** [comment]
I have successfully gotten the paraviewweb visualizer to execute my Reader function, using the smproxy.reader decorator, when i select a csv file in the GUI.  The only problem I am having now is that I cannot connect this new reader pipeline back to the HTML on the client side.  How to I get the python pipeline I just created to appear in the Visualizer pipeline? 

As an example, let's say that my new CSVReader3D.py just creates a sphere:

`
from paraview.util.vtkAlgorithm import *
from paraview import simple
@smproxy.reader(name="CSVReader3DTEST", label="Tester", extensions="csv", file_description="CSV files")
class CSVReader3DTEST():
    def __init__(self):
        sphere = simple.Sphere()
        sphere.Radius = 1
        simple.Show()
        simple.Render()
        return 1
`

**Comment by plasmapotential** [comment]
I have successfully gotten the paraviewweb visualizer to execute my Reader function, using the smproxy.reader decorator, when i select a csv file in the GUI.  The only problem I am having now is that I cannot connect this new reader pipeline back to the HTML on the client side.  How to I get the python pipeline I just created to appear in the Visualizer pipeline? 

As an example, let's say that my new CSVReader3D.py just creates a sphere.  How do I get the sphere to show in the renderview and in the pipeline in the html gui?
```python
from paraview.util.vtkAlgorithm import * 
from paraview import simple    
@smproxy.reader(name="CSVReader3DTEST", label="Tester", extensions="csv", file_description="CSV files")
class CSVReader3DTEST():
    def __init__(self):
        sphere = simple.Sphere()
        sphere.Radius = 1
        simple.Show()
        simple.Render()
        return 1
```

**Comment by jourdain** [comment]
Please read more the examples. They are at the VTK level (Filters), you can not create proxy using simple. 

`class PythonSuperquadricSource(VTKPythonAlgorithmBase):` vs `class CSVReader3DTEST():`

**Comment by plasmapotential** [comment]
It seemed a little extreme to code an entire VTK filter for such a trivial function that already exists in desktop paraview, so I used a different approach.  For other people that cannot import a vector using the CSVReader, I wrote a pvpython script that reads a csv, applies the csvreader then tabletopoints filter, then saves the output into a .vtk file.  I can use the LegacyVTKReader to read the .vtk data.  After I read it in I apply a calculator and gylph filter to get the vector components of my data.

```python
import sys
path = '/opt/paraview/ParaView-5.7.0-MPI-Linux-Python3.7-64bit/lib/python3.7/site-packages'
sys.path.append(path)
from paraview import simple

pc = simple.CSVReader(FileName=['B_pointcloud.csv'])
t2p = simple.TableToPoints(Input=pc)
t2p.XColumn = '# X'
t2p.YColumn = 'Y'
t2p.ZColumn = 'Z'
writer = simple.CreateWriter("test2.vtk", t2p)
writer.UpdatePipeline()

```

**Comment by jourdain** [comment]
What I'm suggesting is to write 2 lines of VTK rather than 2 line of PV. If you look at the example they show you how to use existing VTK filters internally which is exactly what you are looking for (vtkCSVReader+vtkTableToPoint).

**Comment by plasmapotential** [comment]
Thanks for your last comment.  It was unclear that I should be writing VTK directly, but now it is.

I made two classes that both perform the same function.  The first uses the vtkDelimitedTextReader => vtkTableToPolyData, and the second uses numpy genfromtext => numpy_to_vtk => vtkTableToPolyData.  Both methods load my CSV and the vector components contained therein, but the precision seems to be low.  Some of the points are rounded when I display them in the html GUI.  It seems that VTK is only keeping the first 6 significant figures.  Is there a way around this?

Method #1:  vtkDelimitedTextReader => vtkTableToPolyData
```python
@smproxy.reader(name="CSVReader3D", label="CSV TEST",
                extensions="csv", file_description="CSV files")
class CSVReader3D(VTKPythonAlgorithmBase):
    def __init__(self):
        VTKPythonAlgorithmBase.__init__(self, nInputPorts=0, nOutputPorts=1, outputType='vtkPolyData')
        self._filename = None
        self._filename = 'testFile.csv'
        from vtkmodules.vtkIOInfovis import vtkDelimitedTextReader
        from vtkmodules.vtkFiltersGeneral import vtkTableToPolyData

        # Create a Delimited Text Reader object
        self._csv_source = vtkDelimitedTextReader()
        self._csv_source.SetFieldDelimiterCharacters(",")
        self._csv_source.SetHaveHeaders(True)
        self._csv_source.SetDetectNumericColumns(True)
        self._csv_source.SetFileName(self._filename)

        #Convert Text Delimited Object to PolyData (points)
        self._realAlgorithm = vtkTableToPolyData()
        self._realAlgorithm.AddInputConnection(self._csv_source.GetOutputPort())
        self._realAlgorithm.SetXColumnIndex(0)
        self._realAlgorithm.SetYColumnIndex(1)
        self._realAlgorithm.SetZColumnIndex(2)
        self._realAlgorithm.SetXComponent(3)
        self._realAlgorithm.SetYComponent(4)
        self._realAlgorithm.SetZComponent(5)
        self._realAlgorithm.SetXColumn('# X')
        self._realAlgorithm.SetYColumn('Y')
        self._realAlgorithm.SetZColumn('Z')


    @smproperty.stringvector(name="FileName")
    @smdomain.filelist()
    @smhint.filechooser(extensions="csv", file_description="Numpy CSV files")
    def SetFileName(self, name):
        """Specify filename for the file to read."""
        if self._filename != name:
            self._filename = name
            self.Modified()

    def RequestData(self, request, inInfo, outInfo):
        from vtkmodules.vtkCommonDataModel import vtkPolyData
        self._realAlgorithm.Update()
        output = vtkPolyData.GetData(outInfo, 0)
        output.ShallowCopy(self._realAlgorithm.GetOutput())
        output.Update()
        return 1
```


Method #2:  numpy genfromtext => numpy_to_vtk => vtkTableTo PolyData
```python
@smproxy.reader(name="CSVReader3D", label="CSV TEST",
                extensions="csv", file_description="CSV files")
class CSVReader3D(VTKPythonAlgorithmBase):
    def __init__(self):
        VTKPythonAlgorithmBase.__init__(self, nInputPorts=0, nOutputPorts=1, outputType='vtkPolyData')
        self._filename = None
        self._filename = 'testFile.csv'

        import numpy as np
        from paraview.vtk.util import numpy_support
        from vtkmodules.vtkCommonDataModel import vtkTable
        from paraview.vtk import VTK_FLOAT, VTK_DOUBLE
        from vtkmodules.vtkFiltersGeneral import vtkTableToPolyData

        arr = np.genfromtxt(self._filename, dtype=None, skip_header=0, names=True, delimiter=',', autostrip=True)
        tab = vtkTable()
        for name in arr.dtype.names:
            vtkarr = numpy_support.numpy_to_vtk( arr[name], deep=True, array_type=VTK_DOUBLE )
            vtkarr.SetName(name)
            tab.AddColumn(vtkarr)

        #Convert Text Delimited Object to PolyData (points)
        self._realAlgorithm = vtkTableToPolyData()
        self._realAlgorithm.AddInputDataObject(0, tab)
        self._realAlgorithm.SetXColumnIndex(0)
        self._realAlgorithm.SetYColumnIndex(1)
        self._realAlgorithm.SetZColumnIndex(2)
        self._realAlgorithm.SetXComponent(3)
        self._realAlgorithm.SetYComponent(4)
        self._realAlgorithm.SetZComponent(5)
        self._realAlgorithm.SetXColumn('X')
        self._realAlgorithm.SetYColumn('Y')
        self._realAlgorithm.SetZColumn('Z')

    @smproperty.stringvector(name="FileName")
    @smdomain.filelist()
    @smhint.filechooser(extensions="csv", file_description="Numpy CSV files")
    def SetFileName(self, name):
        """Specify filename for the file to read."""
        if self._filename != name:
            self._filename = name
            self.Modified()

    def RequestData(self, request, inInfo, outInfo):
        from vtkmodules.vtkCommonDataModel import vtkPolyData
        self._realAlgorithm.Update()
        output = vtkPolyData.GetData(outInfo, 0)
        output.ShallowCopy(self._realAlgorithm.GetOutput())
        return 1
```

**Comment by jourdain** [comment]
Make sure that the vtkPoints that get generated are using double rather than float.
