### ISSUE TITLE
Modifying Visualizer

### ISSUE THREAD

**Issue by Timanu05** [Kitware/visualizer#86]
Hi everyone, I try to modify Visualizer for a more personalize use of it. When I edit a file I get an error wich I saw on internet is link to prettier config. 

![InkedMicrosoftTeams-image (1)_LI](https://user-images.githubusercontent.com/44799668/85523404-3812bd80-b607-11ea-8608-5798df7ae400.jpg)

I try to resolve it by adding "endOfLine: auto" in prettier config but it give me this:

![j6R9P (1)](https://user-images.githubusercontent.com/44799668/85523448-482a9d00-b607-11ea-8339-e0fd9327d6bc.png)

How could I resolve it ?

**Comment by jourdain** [comment]
`npm run reformat`

**Comment by Timanu05** [comment]
Thanks a lot !
