### ISSUE TITLE
Paraview web visualizer as a component within another web app 

### ISSUE THREAD

**Issue by GUT2060** [Kitware/visualizer#87]
Hi , 
As the title of the issue suggest , i would like to use paraview web visualizer as a component within another web app , to be preciser , here is the scenario ; 

Assuming i have a web app (developed using react js) that i can run locally "localhost:port" , when i click on a button , in some part of the web page (that i'm defining)  i want to have the paraview web visulizer which i can freely manipulate as if i was running it using the installation described in the readme of this repository . 
my question is : is there a tutorial out there on how to procede with this ? if not ,some guidelines would be helpful ! 

Thanks for your time

**Comment by jourdain** [comment]
If you are not looking for some UI modification, you can leverage iFrame and URL arguments (for the iFrame) to load specific dataset.

The best deployment guide for Visualizer or any ParaViewWeb based application are the one using docker.
- http://kitware.github.io/paraviewweb/docs/docker.html
- http://kitware.github.io/paraviewweb/docs/ec2.html
- http://kitware.github.io/paraviewweb/docs/container_overview.html
- http://kitware.github.io/paraviewweb/docs/docker_cheatsheet.html

**Comment by GUT2060** [comment]
@jourdain  thanks , that was helpful . 
what's the approach if i'm looking for UI modification ?

**Comment by jourdain** [comment]
Depending on the level of modification, you can fork Visualizer and make your own version with what ever modification that you see fit. But in general Visualizer is generating dynamically the control UI based on the ParaView proxy definition and that part will be trickier to modify.

**Comment by GUT2060** [comment]
@jourdain  Thank you for your explanations , was really helpful
