### ISSUE TITLE
Deploying paraview web visualizer using Flask

### ISSUE THREAD

**Issue by GUT2060** [Kitware/visualizer#89]
Hi , 
Using this tutorial http://kitware.github.io/paraviewweb/docs/ec2.html , i was able to deploy the visualizer using apache on a Google cloud virtual machine . 

Is there a tutorial on how to do that using flask ? 
Any  guidelines on how to do so would be helpful  

Thanks

**Comment by jourdain** [comment]
Apache just do the proxying. You could use flask to serve what ever you need/want and still use apache on the front to forward the requests to flask.

**Comment by GUT2060** [comment]
@jourdain  thanks
