### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by tldv** [Kitware/visualizer#9]
Am running on an Amazon Linux AMI:
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"

Running "npm install -g pvw-visualizer" yields

/usr/bin/Visualizer -> /usr/lib/node_modules/pvw-visualizer/bin/pvw-visualizer-cli.js
> pvw-visualizer@1.0.11 postinstall /usr/lib/node_modules/pvw-visualizer
> fix-kw-web-suite || true
sh: fix-kw-web-suite: command not found
/usr/lib
└── pvw-visualizer@1.0.11

**Comment by jourdain** [comment]
Did that break? Normally the " || true" is to prevent the script to fail. 
As this command should succeed only when developing.

**Comment by jourdain** [comment]
I've tried on OS X and I do get the message, but everything works as expected.

**Comment by tldv** [comment]
Okay. Maybe I'll wait until a user guide exists before I bother you again. Thanks.

**Comment by jourdain** [comment]
No problem, thanks for trying...

On EC2, you probably don't want/need to install the Visualizer via npm as you only need to serve via Apache the "dist" directory of that repo. But on a local system npm will provide an easy to use command line that will used an install version of ParaView.

While on a real system, you need a launcher and configure Apache for some WebSocket forwarding.

**Comment by tldv** [comment]
Okay thanks, I'll give that a shot. In the meantime, I'm anxious to be the guinea pig for any quick start guide for deployment on AWS EC2. Thanks.

**Comment by jourdain** [comment]
I think the first thing is to understand the pieces that ParaViewWeb needs (PV 4+) and then just replace the html/js code with the new one (at some point). For that you can still use ParaView 5 for the backend for both JS versions.

http://pvw.kitware.com/#!/guide/multi_user_setup

If you get the setup working with the current documentation, then migrating using the new "client" code base should be fairly easy.

Did you tried one of our public AMI already configured with ParaView 4.4 and Visualizer?

**Comment by tldv** [comment]
Thanks. If you have an AMI ID or some other identifier, that would be very useful. The AMI search comes up with nothing.

**Comment by jourdain** [comment]
Ok will do. I'll add a new page on paraviewweb with those IDs. And post back here with the link.

**Comment by tldv** [comment]
I tried using Paraview 5.0.1 for the backend, but Visualizer, in pvw-visualizer.py line 85, raised an ImportError: No module named web in line 85.

Looking in my 5.0.1 install, there doesn't seem to be a web module folder in \lib\paraview-5.0\site-packages\paraview\
