### ISSUE TITLE
mpirun paraview with Visulizer

### ISSUE THREAD

**Issue by ssmns** [Kitware/visualizer#91]
I can't see any option to set thread for running with mpirun/mpiexec 
how can set my thread numbers for post processing with paraview in web

**Comment by jourdain** [comment]
You just need to run `pvbatch` rather than `pvpython`.

`mpirun -n 4 /.../pvbatch ./server/pvw-visualizer.py --data ~/ --port 1234 --content ./www`

**Comment by ssmns** [comment]
jourdain comments can help to use mpi run 
also i use below coomand : 

```
$PARAVIEWPATH/bin/mpiexec -n 4 $PARAVIEWPATH/bin/pvbatch $PARAVIEWPATH/share/paraview-5.8/web/visualizer/server/pvw-visualizer.py --data /home/dcim/ssmns/salam  --port 8081 --content $PARAVIEWPATH/share/paraview-5.8/web/visualizer/www
```
