### ISSUE TITLE
Provide option to set `sessionURL` in pvw-visualizer.py

### ISSUE THREAD

**Issue by phcerdan** [Kitware/visualizer#95]
Hi there @jourdain, instead of providing `--content ./dist`, I would like the `pvw-visualizer.py` to listen to client from another port for development purposes (hot reload). I think the option is named `sessionURL` (inferred from the Vue example [here](https://github.com/Kitware/web-project-templates/blob/0109fd3fdf94cc2769664458d47107aedf7d5594/vue-vtkjs-pvw-template/src/store/wslink.js#L47)),

How can I hack  passing `sessionURL` to the server through `pvw-visualizer.py`?

**Comment by jourdain** [comment]
I'm not sure to follow, but `sessionURL` is what the client use to connect to a running pvw process. So nothing to do with `pvw-visualizer.py`. 

If you want to start `pvw-visualizer.py` on demand from the client, then you need to use the launcher.

**Comment by phcerdan** [comment]
I understand, thanks @jourdain.
I thought it would be possible to avoid using a launcher, as in https://github.com/Kitware/web-project-templates/tree/master/vue-vtkjs-pvw-template, when using port 8080 for the client, and port 1234 (the defaults) for the pvw-server. 

```
$ npm run serve &
$ /.../pvpython ./server/pvpython/pvw-server.py --port 1234

Open your browser to http://localhost:8080/
```

**Comment by phcerdan** [comment]
Well, you can really hack adding `config.sessionURL = 'ws://localhost:1234/ws';`  to `connect` [here](https://github.com/Kitware/visualizer/blob/c2118b5127eca3a7efbdc6a2a20a4c8a08813716/src/app.js#L40).

```js
export function connect(config = {}) {
  loading();
  config.sessionURL = 'ws://localhost:1234/ws'; // <------- HACK TODO for development
  network.onReady(start);
  network.onError(loading);
  network.onClose(() => loading('Server disconnected'));
  network.connect(config);

  // Configure renderer to local if asked for
  if (config.renderer) {
    dispatch(actions.view.setRemoteRendering(config.renderer === 'remote'));
  }
}

```

**Comment by jourdain** [comment]
Or you can pass it in the url by relaying on [that](https://github.com/Kitware/visualizer/blob/c2118b5127eca3a7efbdc6a2a20a4c8a08813716/src/app.js#L52-L56)
