### ISSUE TITLE
Incorrect syntax to start ParaView Web Visualizer in documentation

### ISSUE THREAD

**Issue by AlbertoPa** [Kitware/visualizer#99]
### High-level description

The instructions provided in this document https://kitware.github.io/visualizer/docs/index.html to start ParaviewWeb Visualizer on Windows using the paraview installation are not correct.

The document says to use:

```
$ cd ParaView-5.6.0-Windows-64bit
$ .\bin\pvpython.exe               \
   -m paraview.apps.visualizer      \
   --data "C:\...full_path...\data"  \
   --port 8080

==> Open your browser to http://localhost:8080/
```
However:

- The `-m` option is not recognized and the error `Got unknown argument: -m. Could you have misspelled your Python file path or name?` is returned
- The `\` does not send to a new line
- If the previous issues are addressed, the visualizer is not served, and pointing the browser to https://localhost:8080 returns a 404 error. The --content option seems needed (probably applicable to other OSes?)

The actual syntax, assuming PowerShell or Windows Terminal are used (if ParaView is ParaView-5.6.2-Windows-msvc2015-64bit, which is the name from the Download page. I am using this version because I initially thought the problem was due to a change due to the version, but it was not the case) is:

```
PS C:\> cd ParaView-5.6.2-Windows-msvc2015-64bit

PS C:\ParaView-5.6.2-Windows-msvc2015-64bit>& .\bin\pvpython.exe `
.\share\paraview-5.6\web\visualizer\server\pvw-visualizer.py `
--data "C:\Your\Path\ToData\ToVisualize\"  `
-p 8080 `
--load-file <PathToFileToLoadIfNeededToOpenData> `
--content .\share\paraview-5.6\web\visualizer\www
```

I added `--load-file` because it is needed in some cases to load data (e.g. with the OpenFOAM data reader). With these changes, everything seems to work.

### Environment
- **Visualizer**: Any
- **OS**: Windows 11
- **Browser**: Microsoft Edge Version 94.0.992.50 (Official build) (64-bit)

Thanks!

**Comment by jourdain** [comment]
Good catch `-m` was introduced in PV 5.8.

**Comment by AlbertoPa** [comment]
My bad, you are right: it works in 5.10. Sorr about that.
